---
title: "Maritime Trade"
description: |
  Maritime trade is an important part of any Catan game. We are going to explore the changes and how I implemented maritime trade in this simulation.
author:
  - name: Justin Schultz
    url: {}
date: 2022-03-15
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

In my last post we discussed how we can gather and build different objects depending on what resources we get based on the hex we are built on. While our previous code worked we could come into different problems. One of these problems being when we were not built on a resources hex. This is a very common problem. One of the biggest choices that has to be made in the beginning of a game is if you are going to risk loosing a resource for better a better number on the board. Today we are going to look into Maritime trading for everything between 4 to 1, 3 to 1, and 2 to 1 trading. 

## Building Changes

In order to include trading resources using maritime trades we needed to fix the way we checked to see if we could build an object. This can get very completed but I think that I created an interesting way apply maritime trade.

To start we are going to set the going trade amount for each resource. While at the start this can just be set to 4, during the game you could be built on a 3:1 port (3 resources for 1 of any resources) or a 2:1 port (2 of a specific resources for 1 of any resources). 

```
b_trade = 4
l_trade = 4
g_trade = 4
o_trade = 4
s_trade = 4
```

Since the 3:1 port affects all of the resources and their trade amount. To update these a simple If check will do. 

```
if three == True:
        b_trade = 3
        l_trade = 3
        g_trade = 3
        o_trade = 3
        s_trade = 3
```

The last thing we need to check when it comes to trading is if a specific resources. I checked this last to give us the most accurate trade amount per recourse. this is the trade for brick but it is the same for every other resource.

```
if t_brick == True:
    b_trade = 2
```

## Can we built it?

Now that we have the trade amount for each resources we need to see if we can actually build the object. To do this we are going to look into a new variable that I am calling 's' or Stars. For each object that we are going to build we are going to look at the number of resources needed. For instance to build a road you need a Brick and a Lumber. This means that the star value for this would need to be at lest 2. While a settlement need 4 resources (brick, lumber, grain, and sheep) so our star value will need to be 4.

Lets take a look at the road builder function. 

```
def road_builder(card, three=False, t_brick=False, t_grain=False, t_ore=False, t_sheep=False):
    s = building_resource(card, n_brick=True, n_lumber=True, three=three, t_brick=t_brick, t_grain=t_grain, t_ore=t_ore,t_sheep=t_sheep)
    if s >= 2:
        return True
    else:
        return False
```

To start the road builder function needs to know what cards we have and the trade amount for every resources. We then set the value of 's' and then check to see if 's' is at least 2. taking a close look int the building resources we can start to truly appreciate how 's' works. We will jump into the building_resource function. 

```
if n_brick == True:
    if card['brick'] > 0:
        s += 1
        s += (card['brick']-1)//b_trade
    else:
        s += card['brick']//b_trade
```

This is the brick part of the building resource function. The first thing that this checks is to see if that resource is needed for the object that is being built. if it is and there is more then one of that resources then we add on one star and then it check how many more stars you can get based on the trade amount. If you do not need that resource then you just check to see how many stars you get based on trade. 

While this works for roads, settlements, and development cards this doesn't work with city's because it needs 2 grain and 3 ore to build a city. Lets take a look at what changes we made to allow us to correctly build cities. 

## City Builder

Since cities need 2 grain and 3 ore to build we need to check their star value differently. For each of the other resources the star check stays the same but with grain and ore we made a new check called build city or b_city for short.

```
# Grain
    if n_grain == True:
        if b_city == True:
            if card['grain'] <= 2:
                s += card['grain']
            else:
                s += 2
                s += (card['grain']-2)//g_trade
        else:
            if card['grain'] > 0:
                s += 1
                s += (card['grain']-1)//g_trade
    else:
        s += card['grain']//g_trade

```

There are many similarities between the Grain and ore collection. However, when b_city is true we need to check to see if we have at least 2 grain and 3 ore. Using this we are able to correctly get the correct amount of stars for every possible situation. 

### Miner Changes

While this change is not major I am going to include how many times you would get affected by the robber. This small change counts the number of times you would get affected by the robber 

```
if role == 7:
    if sum(card.values()) > 7:
        robber += 1
```